### PR TITLE
release: v1.0.0a4

### PR DESCRIPTION
**Pull request by hachreak**
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by drjova** [comment]
@lnielsen we'll need and new pypi secret here as well :)

**Comment by lnielsen** [comment]
```
  secure: "IfFRW+vfnxYSEn8ke3vNYS7CdIZD0M+y8qmePQEm8npgwh+oUuKEmO9ijNlripodTo4orBDK2Si7hDtvsyMbI8InCnBCqxIOPJKqRF9PCMBqlHTTAmFWZwg8/SdhRf0/Xk6xZJAIerYLvtVlzSiepvGxCtt9qnsD8lmjhDaqn+Guiv4N9WQ/doHXG5ztXos7H4JNaXGkzHEGsSlUlBPZC8A7jP67wqQER74tNNpLMO7bUq2/zsfSI4cGPhEfVO3wH3j5Rav2tdANIxBmFRHeCec0f9NJU+sIH5FfgYb6IOg6hfixp/9azDPMJZEXWJF1v/bMFmYl+Sf2oo5bg2ppCOLMa+L2Kb9Pos1k6l0ORvlar1k9iakxwr6sH4vVr2Pd9zmxugbVqM76C2hwA4T1lsQ3XKDVCNp/6WSYr/sukyKP2DvLnx0tlakoo9SEsKI8RYW+iwwRLH4zGCgHErFl/BCpvOTF0Td/tYxrhCeBvr6X3RSBxK9SkMnDOnGONMzYhW0VlX701ok7Fh8rZtjIa9qJH6+UepX8UtsqU5XCuzINrz/o2De0Ew0PPw8Y+V1dqpTXFPBkyhQTxLs9GYOpZDhkUyuBwoNv9NJEvkzgV9gxTaBevJ0OEx4ZnAJMrDm96vrttAO4HMgsJA6mQbFGxbcLBz2nZqKNs8eMq038qoE="
```

**Comment by hachreak** [comment]
user `inveniosoftware`, right?

**Comment by drjova** [comment]
@hachreak yep

**Comment by hachreak** [comment]
waiting for https://github.com/inveniosoftware/invenio-admin/pull/59

**Comment by hachreak** [comment]
ping @drjova

**Pull request merged**
