### PR TITLE
tests: addition of test_examples_app.py

### LINKED ISSUE #37: tests: addition of test_example_app.py
The package contains `examples/app.py` example application, but there is no test
for it in `tests/test_example_app.py`.  It should be added.  See existing examples:

- https://github.com/inveniosoftware/invenio-records/blob/master/tests/test_example_app.py
- https://github.com/inveniosoftware/invenio-marc21/blob/master/tests/test_example_app.py

### PR DESCRIPTION
**Pull request by hachreak**
* Adds test_examples_app.py. (closes #37)

Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>

### CODE REVIEW

**Comment by hachreak** [comment]
ping @jirikuncar :shipit: ?

**Comment by lnielsen** [comment]
Needs a rebase.

**Comment by hachreak** [comment]
@lnielsen rebase done

**Comment by hachreak** [comment]
ping @jirikuncar :shipit: ?

**Comment by jirikuncar** [comment]
LGTM

**Comment by jirikuncar** [comment]
@hachreak you need to wait for @lnielsen who is maintainer of this package.

**Comment by lnielsen** [comment]
LGTM

**Pull request merged**
